print("hola!")
print("veo que no eres de por aqui")
nombre=input('como te llamas? ')
print('ya veo', nombre)
pais=input('de que pais eres? ')
print('ohh asi que eres de', pais)
estado=input('de que estado eres? ')
print('si eres de', estado, 'debes de saber tu ciudad')
ciudad=input('de que ciudad eres? ')
print('me esperaba cualquier ciudad menos esa... sorprendente')
especificacion=input('que te gusta de tu ciudad? ')
print('interesante')
specification=input('quieres vivir en algun otro lado? ')
print("mm te entiendo")
specificacion=input('tienes trabajo? ')
print("claro eres un adulto")
aspecification=input('si te ofrecieran una mejor oportunidad de trabajo la aceptarias dejando atras a tus alumnos? ')
print("pues cada quien")
bspecification=input('cual es tu peor alumno? ')
print("chale")
cspecification=input('prefieres la comida salada o dulce? ')
print("digno del profe")
print(" pues eso fue todo espero que le vaya bien.")